@startuml
title Sequence Diagram for HelpCommand (Main Control Flow Only)

autonumber
hide footbox

actor User
participant ":UI" as UI
participant ":InventoryDock" as InventoryDock
participant ":Parser" as Parser
participant ":HelpCommand" as HelpCommand

User -> UI: enter help command
activate UI
UI -> InventoryDock: input
activate InventoryDock
InventoryDock -> Parser: parse(input)
activate Parser

create HelpCommand
Parser -> HelpCommand: HelpCommand()
activate HelpCommand
HelpCommand --> Parser: command
deactivate HelpCommand
Parser --> InventoryDock: command
deactivate Parser

InventoryDock -> HelpCommand: execute(inventory, ui)
activate HelpCommand
HelpCommand -> UI: showHelp()
activate UI
UI --> User: display available commands and User Guide link
deactivate UI

HelpCommand --> InventoryDock: display information
deactivate HelpCommand
deactivate InventoryDock
deactivate UI
@enduml

