@startuml
title FindItemByKeywordCommand Display Flow

autonumber
hide footbox

actor User
participant FindItemByKeywordCommand
participant UI

User -> FindItemByKeywordCommand : execute()
activate FindItemByKeywordCommand

alt matches empty
    FindItemByKeywordCommand -> UI : showNoItemsFound()
    activate UI
    UI --> FindItemByKeywordCommand
    deactivate UI

else else
    FindItemByKeywordCommand -> UI : showDivider()
    activate UI
    UI --> FindItemByKeywordCommand
    deactivate UI

    FindItemByKeywordCommand -> UI : showResultsHeader()
    activate UI
    UI --> FindItemByKeywordCommand
    deactivate UI

    FindItemByKeywordCommand -> UI : showNumberedList()
    activate UI
    UI --> FindItemByKeywordCommand
    deactivate UI

    FindItemByKeywordCommand -> UI : showDivider()
    activate UI
    UI --> FindItemByKeywordCommand
    deactivate UI
end

FindItemByKeywordCommand --> User
deactivate FindItemByKeywordCommand

@enduml
