@startuml
title FindItemByKeywordCommand Parse Flow

autonumber
hide footbox

actor User
participant Parser
participant FindItemParser
participant FindItemByKeywordCommand

User -> Parser : input
activate Parser

Parser -> FindItemParser : parse(input)
activate FindItemParser

alt invalid / missing input
    FindItemParser --> Parser : exception

else else
    FindItemParser -> FindItemByKeywordCommand : new(keyword)
    activate FindItemByKeywordCommand

    FindItemByKeywordCommand -> FindItemByKeywordCommand : initialise fields
    activate FindItemByKeywordCommand
    FindItemByKeywordCommand --> FindItemByKeywordCommand
    deactivate FindItemByKeywordCommand

    FindItemByKeywordCommand --> FindItemParser
    deactivate FindItemByKeywordCommand

    FindItemParser --> Parser : command
    deactivate FindItemParser
end


Parser --> User
deactivate Parser

@enduml
